info: |-
    An interactive scatterplot by Karl Broman.

    The input data is a data frame with column names:
    "x" x coordinate
    "y" y coordinate
    "group" (optional) used for coloring the points.
    "name" (optional) displayed on tooltip when hovering over a point.

original_url: http://www.biostat.wisc.edu/~kbroman/presentations/InteractiveGraphs3/

demo: |-
    n <- 100
    names <- paste0("Gene ", 1:n)
    df <- data.frame(x=rnorm(n), y=rnorm(n), group=sample(c("A","B"), n, replace=TRUE), name = names)
    clickme(df, "scatterplot")

data_names:
    required:
        - "x"
        - "y"
    optional:
        - "group"
        - "name"

params:
    title: "Scatterplot"
    height: 600
    width: 620
    x_axis_label: "x"
    y_axis_label: "y"
    tick_padding: 8
    scale_padding: 0.1
    padding:
        bottom: 90
        left: 100
        top: 0
        right: 10

scripts:
    - d3.v3.min.js
    - plotframe.js

styles:
    - scatterplot.css

require_packages:
    - df2json

require_server: yes

require_coffeescript: no


