get_default_paths <- function(template_name) {

    opts <- list(name = NULL, path = NULL)

    # folder names
    opts$name$template <- template_name
    opts$name$template_assets <- "assets"
    opts$name$clickme_assets <- "clickme_assets"

    # file names
    opts$name$template_file <- "template.Rmd"
    opts$name$config_file <- "config.yml"
    opts$name$translator_file <- "translator.R"
    opts$name$translator_test_file <- "test-translator.R"

    # folder absolute paths
    opts$path$template <- file.path(getOption("clickme_templates_path"), opts$name$template)
    opts$path$template_assets <- file.path(opts$path$template, opts$name$template_assets)
    opts$path$clickme_assets <- file.path(getOption("clickme_output_path"), opts$name$clickme_assets)

    # file absolute paths
    opts$path$template_file <- file.path(opts$path$template, opts$name$template_file)
    opts$path$config_file <- file.path(opts$path$template, opts$name$config_file)
    opts$path$translator_file <- file.path(opts$path$template, opts$name$translator_file)
    opts$path$translator_test_file <- file.path(opts$path$template, opts$name$translator_test_file)

    # relative path (it goes in the HTML files)
    opts$relative_path <- opts$name$clickme_assets

    opts
}

validate_paths <- function(opts) {
    if (!file.exists(getOption("clickme_templates_path")))
        stop(gettextf("getOption(\"clickme_templates_path\") doesn't contain a valid path: %s", getOption("clickme_templates_path")))

    if (!file.exists(opts$path$template))
        stop(gettextf("There is no template %s located in: %s ", opts$name$template, opts$path$template))

    if (!file.exists(opts$path$template_file))
        stop(gettextf("The %s template doesn't contain a template file in: %s ", opts$name$template, opts$path$template_file))

    if (!file.exists(opts$path$config_file))
        stop(gettextf("The %s template doesn't contain a configuration file in: %s ", opts$name$template, opts$path$config_file))

    if (!file.exists(opts$path$translator_file))
        stop(gettextf("The %s template doesn't contain a translator file in: %s ", opts$name$template, opts$path$translator_file))

    if (is.null(getOption("clickme_output_path"))){
        warning(gettextf("getOption(\"clickme_output_path\") was NULL. Using: %s", system.file("output", package = "clickme")))
        options("clickme_output_path" = system.file("output", package = "clickme"))
    } else {
        if (!file.exists(getOption("clickme_output_path")))
            dir.create(getOption("clickme_output_path"))
    }

    invisible()
}

validate_required_packages <- function(opts) {
    if (!is.null(opts$config$require_packages)){
        missing_packages <- opts$config$require_packages[!is.installed(opts$config$require_packages)]

        if (length(missing_packages) != 0){
            message(separator())
            message(gettextf("The %s template requires the following packages:\n\n%s\nPress Enter to install them automatically or \"c\" to cancel.",
                    opts$name$template,
                    paste0(missing_packages, collapse="\n"))
            )
            response <- readline()
            if (tolower(response) == "c"){
                message(gettextf("Try running: install.packages(%s)", paste0(missing_packages, collapse=",")))
                capture.output(return())
            } else {
                install.packages(missing_packages)
            }
            message(separator())
        }

        sapply(opts$config$require_packages, library, character.only = TRUE)
    }

    invisible()
}

validate_assets <- function(opts) {
    sapply(c(opts$config$styles, opts$config$scripts), function(asset){
        if (!grepl("^http", asset)){
            path <- file.path(opts$path$template_assets, asset)
            if (!file.exists(path)) stop(asset, " not found at: ", path)
        }
    })

    invisible()
}

add_params <- function(opts, user_params) {
    opts$params <- opts$config$params
    valid_param_names <- names(opts$config$params)

    for (param in names(user_params)){
        opts$params[[param]] <- user_params[[param]]
    }

    opts
}

#' Get options used by the current template
#'
#' @param template_name name of the reactive
#' @param params named vector or list containing the parameters and values that will be accessible from the template
#' @param name_mappings named vector or list of names in the input data object and the required names they represent. Each element will have the format: name_in_input_data = "required_name"
#' @param data_prefix basename of any temporary files generated by the template, and also used as part of the output HTML file name, default "data"
#' @param html_file_name name of the output HTML file that contains the visualization, default "data_prefix-template.html"
#' @param port port used to open a local browser, default 8000
#' @export
#' @import yaml
get_opts <- function(template_name, params = NULL, name_mappings = NULL, data_prefix = "data", html_file_name = NULL, port = 8000){

    opts <- get_default_paths(template_name)
    validate_paths(opts)

    opts$config <- yaml.load_file(opts$path$config_file)
    validate_required_packages(opts)
    validate_assets(opts)

    # rethink the following lines
    opts <- add_params(opts, params)
    opts$name_mappings <- name_mappings

    opts$data_prefix <- data_prefix %||% basename(tempfile("data"))
    opts$name$html_file <- html_file_name %||% paste0(opts$data_prefix, "-", opts$name$template, ".html")
    opts$path$html_file <- file.path(getOption("clickme_templates_path"), opts$name$html_file)

    if (opts$config$require_server){
        opts$url <- paste0("http://localhost:", port, "/", opts$name$html_file)
    } else {
        opts$url <- opts$path$html_file
    }

    opts
}
