add_ractive_opts <- function(ractive) {
    opts <- list()

    # folder names
    opts$name$ractive <- ractive
    opts$name$data <- "data"
    opts$name$template <- "template"
    opts$name$external <- "external"

    # file names
    opts$name$template_file <- "template.Rmd"
    opts$name$template_config_file <- "template_config.yml"
    opts$name$translator_file <- "translator.R"
    opts$name$translator_test_file <- "test-translator.R"

    # folder absolute paths
    # PONDER: ractive is directly below the root path, maybe in the future we can allow nested paths for ractives (although, simple is better)
    opts$path$ractive <- file.path(get_root_path(), opts$name$ractive)
    opts$path$data <- file.path(opts$path$ractive, opts$name$data)
    opts$path$template <- file.path(opts$path$ractive, opts$name$template)
    opts$path$external <- file.path(opts$path$ractive, opts$name$external)

    # file absolute paths
    opts$path$template_file <- file.path(opts$path$template, opts$name$template_file)
    opts$path$template_config_file <- file.path(opts$path$template, opts$name$template_config_file)
    opts$path$translator_file <- file.path(opts$path$template, opts$name$translator_file)
    opts$path$translator_test_file <- file.path(opts$path$template, opts$name$translator_test_file)

    # paths relative to opts$path$ractive
    opts$relative_path$data <- file.path(opts$name$ractive, opts$name$data)
    opts$relative_path$external <- file.path(opts$name$ractive, opts$name$external)

    opts
}

#' Get options used by the current ractive
#'
#' @param ractive name of the reactive
#' @param params named vector or list containing the parameters and values that will be accessible from the template
#' @param name_mappings named vector or list of names in the input data object and the required names they represent. Each element will have the format: name_in_input_data = "required_name"
#' @param data_prefix basename of any temporary files generated by the ractive, and also used as part of the output HTML file name, default "data"
#' @param html_file_name name of the output HTML file that contains the visualization, default "data_prefix-ractive.html"
#' @param port port used to open a local browser, default 8000
#' @export
#' @import yaml
get_opts <- function(ractive, params = NULL, name_mappings = NULL, data_prefix = "data", html_file_name = NULL, port = 8000){
    opts <- add_ractive_opts(ractive)

    if (!file.exists(opts$path$ractive)) stop("No ractive named ", ractive, " found at:", get_root_path())
    if (!file.exists(opts$path$template_config_file)) stop("No template configuration file found at:", opts$path$template_config_file)

    opts$template_config <- yaml.load_file(opts$path$template_config_file)
    opts <- validate_ractive(opts)

    opts$params <- params
    opts$name_mappings <- name_mappings # TODO: delete this

    opts$data_prefix <- data_prefix %||% basename(tempfile("data"))
    opts$name$html_file <- html_file_name %||% paste0(opts$data_prefix, "-", opts$name$ractive, ".html")
    opts$path$html_file <- file.path(get_root_path(), opts$name$html_file)

    if (opts$template_config$require_server){
        opts$url <- paste0("http://localhost:", port, "/", opts$name$html_file)
    } else {
        opts$url <- opts$path$html_file
    }

    opts
}